current_shell = true
long_kernel = true
long_shell = false
long_uptime = false
physical_cores = true
theme = "default"
show = ["Battery", "Backlight", "Host", "Kernel", "Memory", "Processor", "ProcessorLoad", "Uptime"]
